"""Detection signals — three independent detectors, each returning an AI-likelihood in [0,1].

  Signal 1  signal_llm        semantic/voice judgment via Groq (RepairSafe shape:
                              build prompt -> chat completion -> parse -> validate -> FAIL-CLOSED).
  Signal 2  signal_stylometry statistical form: sentence-length burstiness, MATTR, punctuation.
  Signal 3  signal_lexical    surface fingerprint: phrases LLMs overuse (ensemble stretch).

"Fail closed" means: on any parse/validation failure (Signal 1) or too-short text (Signal 2) we
return a neutral 0.5, so an error can never produce a confident "AI" accusation. Fusion of the
three scores into one verdict lives in scoring.py.
"""
import json
import re
import statistics

from groq import Groq

from config import GROQ_API_KEY, LLM_MODEL

_client = Groq(api_key=GROQ_API_KEY)

_SYSTEM_PROMPT = (
    "You are a forensic text analyst estimating whether a piece of writing was generated by an AI "
    "language model or written by a human. Judge holistically: voice, idiosyncrasy, and whether the "
    "phrasing feels generic/evenly-hedged (AI-leaning) or varied and personal (human-leaning).\n\n"
    "Respond with ONLY a JSON object, no prose, in exactly this shape:\n"
    '{"ai_likelihood": <integer 0-100>, "reasoning": "<one short sentence>"}\n'
    "Where 0 means certainly human and 100 means certainly AI-generated."
)


def _extract_json(raw: str) -> dict:
    """Parse the model's JSON, tolerating stray text around it."""
    try:
        return json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        match = re.search(r"\{.*\}", raw or "", re.DOTALL)
        if not match:
            raise ValueError(f"no JSON object found in response: {raw!r}")
        return json.loads(match.group(0))


def signal_llm(text: str) -> dict:
    """Return Signal 1's assessment of `text`.

    Output:
        {"name": "llm", "score": 0.0-1.0, "reasoning": str, "available": bool}
    where score is AI-likelihood (0 = human, 1 = AI).
    """
    try:
        resp = _client.chat.completions.create(
            model=LLM_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        data = _extract_json(resp.choices[0].message.content)
        likelihood = float(data["ai_likelihood"])
        score = max(0.0, min(1.0, likelihood / 100.0))
        return {
            "name": "llm",
            "score": score,
            "reasoning": str(data.get("reasoning", "")).strip(),
            "available": True,
        }
    except Exception as exc:  # fail closed -> neutral, never a confident AI call
        return {
            "name": "llm",
            "score": 0.5,
            "reasoning": f"unparseable — treated as uncertain ({exc})",
            "available": False,
        }


# ---------------------------------------------------------------------------
# Signal 2 — stylometric heuristics (pure Python, no network)
# Three sub-metrics -> three AI-likelihoods -> weighted combine. See planning.md §1.
# ---------------------------------------------------------------------------

_MATTR_WINDOW = 50
_EXPRESSIVE_MARKS = {";", ":", "—", "–", "(", ")", "?"}


def _clamp01(x: float) -> float:
    return max(0.0, min(1.0, x))


def _linear_ai(value: float, human_at: float, ai_at: float) -> float:
    """Map a metric to an AI-likelihood: `human_at` -> 0.0, `ai_at` -> 1.0, linear/clamped between."""
    return _clamp01((human_at - value) / (human_at - ai_at))


def _sentence_lengths(text: str) -> list[int]:
    parts = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    return [len(p.split()) for p in parts]


def _mattr(tokens: list[str], window: int = _MATTR_WINDOW) -> float:
    """Moving-average type-token ratio (length-robust lexical diversity)."""
    if not tokens:
        return 0.0
    if len(tokens) <= window:
        return len(set(tokens)) / len(tokens)
    ratios = []
    for i in range(len(tokens) - window + 1):
        chunk = tokens[i : i + window]
        ratios.append(len(set(chunk)) / window)
    return sum(ratios) / len(ratios)


def signal_stylometry(text: str) -> dict:
    """Return Signal 2's assessment of `text`.

    Output:
        {"name": "stylometry", "score": 0-1, "metrics": {...},
         "available": True, "low_reliability": bool}
    where score is AI-likelihood (0 = human, 1 = AI).
    """
    word_count = len(text.split())
    sent_lengths = _sentence_lengths(text)
    tokens = re.findall(r"[a-z']+", text.lower())

    # Burstiness: coefficient of variation of sentence length. Low CV -> uniform -> AI.
    if len(sent_lengths) >= 2 and statistics.mean(sent_lengths) > 0:
        cv = statistics.stdev(sent_lengths) / statistics.mean(sent_lengths)
    else:
        cv = 0.0
    ai_burst = _linear_ai(cv, human_at=0.60, ai_at=0.30)

    # Lexical diversity (MATTR). Middling diversity -> AI-leaning.
    mattr = _mattr(tokens)
    ai_mattr = _linear_ai(mattr, human_at=0.75, ai_at=0.55)

    # Punctuation variety: number of distinct "expressive" marks present. Sparse -> AI-leaning.
    distinct_marks = len({c for c in text if c in _EXPRESSIVE_MARKS})
    ai_punct = _clamp01((3 - distinct_marks) / 3)

    score = _clamp01(0.50 * ai_burst + 0.25 * ai_mattr + 0.25 * ai_punct)

    # Length guard (fail-closed): too short for stable stats -> neutral + flag.
    low_reliability = word_count < 40 or len(sent_lengths) < 3
    if low_reliability:
        score = 0.5

    return {
        "name": "stylometry",
        "score": round(score, 4),
        "metrics": {
            "word_count": word_count,
            "sentence_count": len(sent_lengths),
            "cv": round(cv, 4),
            "mattr": round(mattr, 4),
            "distinct_marks": distinct_marks,
            "ai_burst": round(ai_burst, 4),
            "ai_mattr": round(ai_mattr, 4),
            "ai_punct": round(ai_punct, 4),
        },
        "available": True,
        "low_reliability": low_reliability,
    }


# ---------------------------------------------------------------------------
# Signal 3 — lexical "AI-tell" detector (pure Python, no network)
# Matches a curated surface fingerprint of phrases/words LLMs overuse. Distinct from stylometry
# (statistical form) and the LLM (meaning). Asymmetric: markers are positive evidence of AI;
# their absence is only weak evidence of human. See planning.md "Ensemble detection".
# ---------------------------------------------------------------------------

_AI_TELLS = [
    "it is important to note",
    "it is worth noting",
    "it is essential to",
    "furthermore",
    "moreover",
    "in conclusion",
    "in summary",
    "overall",
    "paradigm shift",
    "delve",
    "tapestry",
    "leverage",
    "underscore",
    "navigate the complexities",
    "in today's fast-paced",
    "in the realm of",
    "plays a crucial role",
    "plays a vital role",
    "a testament to",
    "ever-evolving",
    "ever-changing",
    "robust",
    "seamless",
    "holistic",
    "cutting-edge",
    "transformative",
    "multifaceted",
    "foster",
    "realm",
    "comprehensive",
]


def signal_lexical(text: str) -> dict:
    """Return Signal 3's assessment of `text`.

    Output:
        {"name": "lexical", "score": 0-1, "distinct_markers": int, "total_hits": int,
         "markers": [...], "available": True}
    where score is AI-likelihood (0 = human, 1 = AI), driven by how many *distinct* AI-tell
    markers appear. Absence of markers yields a mildly human-leaning 0.45 (weak evidence).
    """
    lowered = text.lower()
    found = []
    total_hits = 0
    for phrase in _AI_TELLS:
        count = lowered.count(phrase)
        if count:
            found.append(phrase)
            total_hits += count

    distinct = len(found)
    # 0 markers -> 0.45 (mild human lean); each distinct marker adds 0.13, capped at 0.95.
    score = _clamp01(0.45 + 0.13 * distinct)
    score = min(score, 0.95)

    return {
        "name": "lexical",
        "score": round(score, 4),
        "distinct_markers": distinct,
        "total_hits": total_hits,
        "markers": found,
        "available": True,
    }
