"""Detection signals.

Signal 1 (LLM, this milestone) follows the RepairSafe shape:
    build prompt -> single chat completion -> parse -> validate -> FAIL-CLOSED fallback.

"Fail closed" here means: on any parse/validation failure we return a neutral 0.5 and mark the
signal unavailable, so an error can never produce a confident "AI" accusation.

Signal 2 (stylometry) and score fusion are added in Milestone 4.
"""
import json
import re

from groq import Groq

from config import GROQ_API_KEY, LLM_MODEL

_client = Groq(api_key=GROQ_API_KEY)

_SYSTEM_PROMPT = (
    "You are a forensic text analyst estimating whether a piece of writing was generated by an AI "
    "language model or written by a human. Judge holistically: voice, idiosyncrasy, and whether the "
    "phrasing feels generic/evenly-hedged (AI-leaning) or varied and personal (human-leaning).\n\n"
    "Respond with ONLY a JSON object, no prose, in exactly this shape:\n"
    '{"ai_likelihood": <integer 0-100>, "reasoning": "<one short sentence>"}\n'
    "Where 0 means certainly human and 100 means certainly AI-generated."
)


def _extract_json(raw: str) -> dict:
    """Parse the model's JSON, tolerating stray text around it."""
    try:
        return json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        match = re.search(r"\{.*\}", raw or "", re.DOTALL)
        if not match:
            raise ValueError(f"no JSON object found in response: {raw!r}")
        return json.loads(match.group(0))


def signal_llm(text: str) -> dict:
    """Return Signal 1's assessment of `text`.

    Output:
        {"name": "llm", "score": 0.0-1.0, "reasoning": str, "available": bool}
    where score is AI-likelihood (0 = human, 1 = AI).
    """
    try:
        resp = _client.chat.completions.create(
            model=LLM_MODEL,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        data = _extract_json(resp.choices[0].message.content)
        likelihood = float(data["ai_likelihood"])
        score = max(0.0, min(1.0, likelihood / 100.0))
        return {
            "name": "llm",
            "score": score,
            "reasoning": str(data.get("reasoning", "")).strip(),
            "available": True,
        }
    except Exception as exc:  # fail closed -> neutral, never a confident AI call
        return {
            "name": "llm",
            "score": 0.5,
            "reasoning": f"unparseable — treated as uncertain ({exc})",
            "available": False,
        }
